version: 2
jobs:
  build:
    working_directory: ~/elixir-app
    docker:
      - image: elixir:1.4.4
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DATABASE: hphoenix_test
    steps:
      - checkout
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
