version: 2
jobs:
  build:
    working_directory: ~/elixir-app
    docker:
      - image: trenpixster/elixir:1.4.4
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hphoenix_test
    steps:
      - checkout
      - run: mix deps.get
      - run: MIX_ENV=test mix ecto.migrate
      - run: mix test
