version: 2
jobs:
  build:
    working_directory: ~/cci-demo-phoenix
    docker:
      - image: trenpixster/elixir:1.3.2
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DATABASE: hphoenix_test
    steps:
      - checkout
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
